package com.company.oop.taskmanagement.commands.enums;

public enum CommandType {

    REGISTERMEMBER,
    LOGIN,
    LOGOUT,
    SHOWMEMBERS,
    SHOWMEMBERACTIVITY,
    CREATETEAM,
    SHOWTEAMS,
    SHOWTEAMACTIVITY,
    ADDMEMBERTOTEAM,
    SHOWALLTEAMMEMBERS,
    CREATEBOARD,
    SHOWTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CREATEBUG,

    CREATEFEEDBACK,

    CREATESTORY,

    CHANGEPRIORITY,
    CHANGESEVERITY,
    CHANGESTATUS,
    CHANGESIZE,
    CHANGERATING,
    ASSIGN,
    UNASSIGN,
    ADDCOMMENT;
}
